server:
  port: 8082

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:5001/bd_save_heritage
    username: root
    # FIXME: remove password from here
    password: Zxsw21qaZ!
    driver-class-name: com.mysql.cj.jdbc.Driver

fileresources:
  storange:   fileSystem #db
  path: /savedimages